# Rechnen mit Vektoren und Matrizen

In numerischen Anwendungen sind Matrizen und Vektoren allgegenwärtig. In Julia sind die entsprechenden Datentypen und Operationen änlich wie in Matlab eingebaut. Allerdings müssen für bestimmte Aufgaben Pakete importiert werden.

## Grundlagen

In Julia sind Vektoren und Matrizen Spezialfälle von $n$-dimensionalen Arrays für einen Vektor gilt $n = 1$ und für eine Matrix $n = 2$.
Uns wird das in der Regel ausreichen aber prinzipiell kann man auch mit fünfdimensionalen Arrays rechnen.

### Erzeugen

Eine erste Möglichkeit Vektoren und Matrizen zu erzeugen besteht darin, die **Einträge direkt anzugeben**:

In [13]:
u = [1 2 3]
x = [5; 1; 9; 2]
y = [1; 2; 1; 3]
A = [1 2 3 4; 7 6 5 4; 6 4 6 4]
B = [2 1; 5 6; 9 1];

Damit haben wir den Zeilenvektor u erzeugt (eine $1 \times 3$ Matrix)

In [14]:
u

1×3 Matrix{Int64}:
 1  2  3

Demgegenüber entsprechen x und y den Vektoren, wie sie überlicherweise in der Mathematik verwendet werden:

In [15]:
x

4-element Vector{Int64}:
 5
 1
 9
 2

In [16]:
y

4-element Vector{Int64}:
 1
 2
 1
 3

Bei A und B handelt es sich um "normale" Matrizen

In [17]:
A

3×4 Matrix{Int64}:
 1  2  3  4
 7  6  5  4
 6  4  6  4

Aufgabe
- Wie funktioniert die Eingabe?

Weiterhin gibt es Funktionen, mit denen sich **spezielle Matrizen und Vektoren** anlegen lassen.

In [18]:
println("    Nullvektor: ", zeros(3))
println("    Nullmatrix: ", zeros(2, 3))
println("    Einsmatrix: ", ones(4, 2))

    Nullvektor: [0.0, 0.0, 0.0]
    Nullmatrix: [0.0 0.0 0.0; 0.0 0.0 0.0]
    Einsmatrix: [1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0]


Auf die Einheitsmatrix werden wir später eingehen.

Praktisch ist die Funktion `range`, die ein Intervall von $a$ bis $b$ in $n - 1$ gleichlange Abschnitte unterteilt.

In [19]:
x = range(1, 5, 6)

1.0:0.8:5.0

Es handelt sich wieder um ein spezielles Objekt für das die einzelnen Werte erst berechnet werden, wenn man sie braucht. Mit `collect` wird daraus wieder ein Vektor.

In [20]:
collect(x)

6-element Vector{Float64}:
 1.0
 1.8
 2.6
 3.4
 4.2
 5.0

### Eigenschaften von Arrays

Die Eigenschaften eines Arrays lassen sich mit verschiedenen Funktionen abfragen.

In [21]:
println("length(x) = ", length(x))
println("ndims(A) = ", ndims(A))
println("size(A) = ", size(A))
println("size(A, 1) = ", size(A, 1))
println("size(A, 2) = ", size(A, 2))

length(x) = 6
ndims(A) = 2
size(A) = (3, 4)
size(A, 1) = 3
size(A, 2) = 4


### Auf Einträge zugreifen

Um auf die Einträge von Arrays zuzugreifen verwendet man eckige Klammern `[]`, die Indizierung
beginnt bei 1. Bei Matrizen werden Zeilen- und Spaltenindex durch ein Komma getrennt.

In [22]:
A[1, 2] = 999
println("A = ", A)
println("x[0] = ", x[2])

A = [1 999 3 4; 7 6 5 4; 6 4 6 4]
x[0] = 1.8


Mit `end` wird vom Ende des Arrays gezählt. Dabei liefert `end` das letzte Element, `end - 1` das vorletzte, usw.

In [23]:
println("A = ", A)
println("A[end, end-2] = ", A[end, end - 1])

A = [1 999 3 4; 7 6 5 4; 6 4 6 4]
A[end, end-2] = 6


Häufig möchte man in einem Rechenschritt auf mehrere Einträge eines Arrays gleichzeitig zugreifen. Hierfür gibt es zwei Möglichkeiten:

- Den Doppelpunkt-Operator
- Die Indizierung mithilfe von Integer-Arrays 

#### Doppelpunkt-Operator

Die Schreibweisen `start:stop` oder `start:inc:stop` zur Erzeugung einer Sequenz von Zahlen haben wir bereits kennengelernt. Eine solche Sequenz kann zur Indizierung verwendet werden:

In [24]:
y = [9; 3; 5; 1; 7; 4; 99];
println("y = ", y)
println("y[2:4] = ", y[2:5])
println("y[3:end] = ", y[3:end])

y = [9, 3, 5, 1, 7, 4, 99]
y[2:4] = [3, 5, 1, 7]
y[3:end] = [5, 1, 7, 4, 99]


Offenbar kann man auch hier wieder `end` verwenden.

Die Adressierung mit dem Doppelpunkt funktioniert auch bei Zuweisungen. Hier ein Beispiel:

In [25]:
A = [1 2 3 4; 5 6 7 8; 9 10 11 12]
println("A =")
display(A)
A[1:3, 3:4] = [11 22; 77 88; 99 11]
println("A =")
display(A)


A =


3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

A =


3×4 Matrix{Int64}:
 1   2  11  22
 5   6  77  88
 9  10  99  11

Wichtig dabei ist, dass die Dimensionen links und rechts vom Gleichheitszeichen zusammenpassen.

#### Index-Arrays

Mithilfe von Index-Arrays lassen sich nicht-fortlaufende Bereiche adressieren

In [26]:
x = [1 2 3 4 5 6 7]
println("x = ", x)
x[[1 3 7]] = [11 33 77]
println("x = ", x)

x = [1 2 3 4 5 6 7]
x = [11 2 33 4 5 6 77]


## Rechnen mit Matrizen und Vektoren

In Julia ist es möglich, Rechnungen mit Matrizen und Vektoren sehr kompakt und fast wie auf dem Papier aufzuschreiben.

### Rechenoperation

Die mathematischen Operatoren `+, -, *` sind fast so definiert, wie wir das aus der Mathematik kennen, wobei man für das Matrix-Vektor-Produkt $\mathbf{A}\mathbf{x}$ in Julia `A*x` schreibt.

In [41]:
x = [5; 1; 6]

3-element Vector{Int64}:
 5
 1
 6

In [28]:
y = [9; 13; 8]

3-element Vector{Int64}:
  9
 13
  8

In [29]:
A = [1 2 3; 5 4 3]

2×3 Matrix{Int64}:
 1  2  3
 5  4  3

In [30]:
B = [1 1; 2 2; 3 3]

3×2 Matrix{Int64}:
 1  1
 2  2
 3  3

In [31]:
x + 2*y

3-element Vector{Int64}:
 23
 27
 22

Eine Besonderheit in Julia ist, dass man das *-Zeichen zwischen einer Zahl und einer Variablen auch weglassen kann:

In [34]:
5x - 2y

3-element Vector{Int64}:
   7
 -21
  14

In [32]:
A*x

2-element Vector{Int64}:
 25
 47

In [33]:
A*B

2×2 Matrix{Int64}:
 14  14
 22  22

Mit einem angehängten Apostroph `'` wird eine Matrix oder eines Vektors transponiert.

In [43]:
A'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  5
 2  4
 3  3

In [44]:
x'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 5  1  6

Dabei ist die Transponierte eines Vektors ein Zeilenvektor, lassen Sie sich von dem Wort `adjoint` nicht abschrecken, für uns hat es keine tiefergehende Bedeutung.

### Elementweise Operationen

Manchmal möchte man Operationen elementweise anwenden, zum Beispiel zu jedem Eintrag des Vektors eine Zahl addieren oder für alle Einträge den Sinus berechnen. Hierzu wird in Julia (das ist durchgängig so) an die Funktion oder den Operator ein Punkt angehängt (in Matlab gibt es die Konvention auch, dort ist sie aber nicht durchgängig umgesetzt).

In [36]:
x .+ 5

3-element Vector{Int64}:
 10
  6
 11

In [37]:
sin.(x)

3-element Vector{Float64}:
 -0.9589242746631385
  0.8414709848078965
 -0.27941549819892586

Das Prinzip funktioniert auch wenn beide Operanden Arrays sind, zum Beispiel führt `.*` eine Elementweise Multiplikation aus.

In [39]:
x .* y

3-element Vector{Int64}:
 45
 13
 48

### Lineare Algebra

Um Funktionen aus dem Gebiet der Linearen Algebra zu nutzen, wird zunächst das entsprechende Paket importiert.

In [2]:
using LinearAlgebra

Das Skalarprodukt von zwei Vektor berechnet `dot` oder der `⋅` (Eingabe mit `\cdot`)

In [47]:
println("x ⋅ y = ", x ⋅ y)
println("dot(x, y) = ", dot(x, y))

x ⋅ y = 106
dot(x, y) = 106


während es für das Kreuzprodukt kein eigenes Symbol gibt

In [5]:
u = [3; 2; 1]
v = [5; -1; 4]
w = cross(u, v)

println("u = ", u)
println("v = ", v)
println("w = (u x v) = ", w)
println("Natürlich gilt u ⋅ w = ", u ⋅ w, " und v ⋅ w = ", v ⋅ w)

u = [3, 2, 1]
v = [5, -1, 4]
w = (u x v) = [9, -7, -13]
Natürlich gilt u ⋅ w = 0 und v ⋅ w = 0


Lineare Gleichungssysteme lassen sich mit dem `\` - Operator lösen.

In [9]:
A = [5  2; 6 1]
b = [5; 2]
x = A \ b

2-element Vector{Float64}:
 -0.14285714285714288
  2.857142857142857

Die Verwendung des `\`-Operators kann man sich schlecht merken (findet der Autor). Vielleicht hilft folgende Erklärung. Auf Englisch heißt der Operator _left-division_ Operator, was sich folgendermaßen verstehen lässt. Wir beginnen mit dem einfachen Fall der skalaren Gleichung $ax = b$, die man dadurch löst, dass man auf beiden Seiten durch $a$ dividiert und damit $ax / a = b / a$ also $x = b/a$ erhält. Für die Vektorgleichung

$$
    \mathbf{A}\mathbf{x} = \mathbf{b}
$$

kann man aber nicht einfach durch $\mathbf{A}$ teilen. Man schreibt stattdessen

$$
    \mathbf{A} \backslash \mathbf{A} \mathbf{x} = \mathbf{A} \backslash \mathbf{b}
$$

und meint mit $\mathbf{A} \backslash$ nichts anderes als die Multiplikation mit der Inversen $\mathbf{A}^1$. Also sozusagen dividieren von links, daher der Divisionsstrich in die andere Richtung. Mit dieser Überlegung ist

$$
    \underbrace{\mathbf{A} \backslash \mathbf{A}}_\mathbf{I} \mathbf{x} = \mathbf{A} \backslash \mathbf{b} \iff \mathbf{x} = \mathbf{A} \backslash \mathbf{b}
$$

und die Schreibweise damit durchaus sinnvoll. Mit $\mathbf{I}$ ist die Einheitsmatrix gemeint, im Zweifelsfall nochmal im Skript Mathematik I nachlesen. Und: Googeln Sie mal '_matrix left division_' - die Schreibweise ist ziemlich weit verbreitet.

Zum Schluss noch die obligatorische Kontrolle

In [10]:
A*x - b

2-element Vector{Float64}:
 0.0
 0.0

Für die Einheitsmatrix 

$$
    \mathbf{I} 
    =
    \left[
        \begin{array}{ccccc}
            1 & 0 & 0 & \cdots & 0 \\
            0 & 1 & 0 & \cdots & 0 \\
            0 & 0 & 1 & \cdots & 0 \\
            \vdots & \vdots & \vdots & \ddots & \vdots \\
            0 & 0 & 0 & \cdots & 1
        \end{array}
    \right]
$$

wird in Julia das Symbol `I` verwendet, für das man keine Größe angeben muss, es funktioniert, wie man das aus der Mathematik kennt. Zum Beispiel bei der Multiplikation mit einem Vektor

In [13]:
I * u

3-element Vector{Int64}:
 3
 2
 1

oder der Addition zu einer anderen Matrix (auf der Diagonalen von $A$ stehen $5$ und $1$).

In [14]:
A + I

2×2 Matrix{Int64}:
 6  2
 6  2

Exkurs: Interessanterweise belegt `I` dabei genau ein Byte Speicherplatz, während Vektoren einen gewissen Overhead und für jeden double-Werte 8 Bytes benötigen.

In [26]:
println("Einheitsmatrix: ", Base.summarysize(I))
println("Speicher für Vektor mit   3 Elementen: ", Base.summarysize([1.0, 2.0, 3.0]))
println("Speicher für Vektor mit   4 Elementen: ", Base.summarysize([1.0, 2.0, 3.0, 4.0]))

Einheitsmatrix: 1
Speicher für Vektor mit   3 Elementen: 64
Speicher für Vektor mit   4 Elementen: 72


Die Nullen werden also gar nicht gespeichert. Wie funktioniert das? In Julia können Funktionen und Operatoren unterschiedlich für verschiedene Datentypen implementiert werden. Es gibt also eine spezielle Version von `*` für die Einheitsmatrix und einen Vektor, der einfach den Vektor zurückliefert. Das ist eine sehr schöne Anwendung eines der fundamentalen Konzepte von Julia, dem _Multiple Dispatch_. Ein Vortrag zum Thema gibt es hier https://youtu.be/kc9HwsxE1OY, Stefan Karpinski ist einer der Autoren von Julia, dementsprechend ist er ziemlich begeistert von der Sache. Trotzdem intressant.